### ISSUE TITLE
Develop skeleton layout

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/whoi-plankton#1]

**Comment by joefutrelle** [comment]
* Use only bootstrap CSS classes
* Navbar and body independently scrollable

**Comment by joefutrelle** [comment]
![image](https://user-images.githubusercontent.com/2365298/115592410-30f92200-a2a1-11eb-8cdc-fb4dd495ce26.png)

**Comment by mayaapeterson** [comment]
I pushed the skeleton layout with bootstrap CSS classes and am still working on the independent scrollable feature of the navbar.

**Comment by mayaapeterson** [comment]
Added the independently scrollable side nav bar to the skeleton layout
